## Visualize dataset using categorical embedding

The dataset for this project originates from the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Census+Income). The datset was donated by Ron Kohavi and Barry Becker, after being published in the article _"Scaling Up the Accuracy of Naive-Bayes Classifiers: A Decision-Tree Hybrid"_. We can find the article by Ron Kohavi [online](https://www.aaai.org/Papers/KDD/1996/KDD96-033.pdf). The data we investigate here consists of small changes to the original dataset, such as removing the `'fnlwgt'` feature and records with missing or ill-formatted entries.

In [1]:
import warnings
warnings.simplefilter('ignore')

# Import libraries necessary for this project
import numpy as np
import pandas as pd
from time import time
from IPython.display import display # Allows the use of display() for DataFrames

# Import sklearn.preprocessing.StandardScaler
from sklearn.preprocessing import MinMaxScaler

# Import train_test_split
from sklearn.model_selection import train_test_split

# Import two metrics from sklearn - fbeta_score and accuracy_score
from sklearn.metrics import fbeta_score
from sklearn.metrics import accuracy_score

# Import the three supervised learning models from sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Import 'GridSearchCV', 'make_scorer', and any other necessary libraries
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer

# Import functionality for cloning a model
from sklearn.base import clone

import altair as alt
alt.data_transformers.enable('json')

# Pretty display for notebooks
%matplotlib inline

from gensim.models import Word2Vec

# TSNE
import time
from sklearn.manifold import TSNE

In [2]:
# Load the Census dataset
data = pd.read_csv("census.csv")

data.head()

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K

**Featureset Exploration**

* **age**: Continuous. 
* **workclass**: Categorical - Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked. 
* **education**: Categorical - Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool. 
* **education-num**: Continuous. 
* **marital-status**: Categorical - Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse. 
* **occupation**: Categorical - Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces. 
* **relationship**: Categorical - Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried. 
* **race**: Categorical - Black, White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other. 
* **sex**: Categorical - Female, Male. 
* **capital-gain**: Continuous. 
* **capital-loss**: Continuous. 
* **hours-per-week**: Continuous. 
* **native-country**: Categorical - United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

----
## Preparing the Data
Before data can be used as input for machine learning algorithms, it often must be cleaned, formatted, and restructured. Fortunately, for this dataset, there are no invalid or missing entries we must deal with, however, there are some qualities about certain features that must be adjusted.

### Normalizing Numerical Features
In addition to performing transformations on features that are highly skewed, it is often good practice to perform some type of scaling on numerical features. Applying a scaling to the data does not change the shape of each feature's distribution (such as `'capital-gain'` or `'capital-loss'` above); however, normalization ensures that each feature is treated equally when applying supervised learners. Note that once scaling is applied, observing the data in its raw form will no longer have the same original meaning.

In [3]:
# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler() # default=(0, 1)
numerical = ['age', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
numerical_normalized = ['age_normalized', 'education-num_normalized', 'capital-gain_normalized',
                        'capital-loss_normalized', 'hours-per-week_normalized']

normalized_data = data
normalized_data[numerical_normalized] = data[numerical]

normalized_data[numerical_normalized] = scaler.fit_transform(normalized_data[numerical_normalized])

normalized_data.head()

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,age_normalized,education-num_normalized,capital-gain_normalized,capital-loss_normalized,hours-per-week_normalized
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K,0.301370,0.800000,0.02174,0.0,0.397959
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,0.452055,0.800000,0.00000,0.0,0.122449
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K,0.287671,0.533333,0.00000,0.0,0.397959
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K,0.493151,0.400000,0.00000,0.0,0.397959
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K,0.150685,0.800000,0.00000,0.0,0.397959

In [4]:
categorical = ['workclass', 'education_level', 'marital-status', 'occupation', 'relationship',
               'race', 'sex', 'native-country']

def getSentence(x):
    arr = []
    for col in categorical:
        arr.append(x[col].strip())
    return arr

In [5]:
normalized_data['combined-categories'] = normalized_data.apply(getSentence, axis=1)
normalized_data.head()

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,age_normalized,education-num_normalized,capital-gain_normalized,capital-loss_normalized,hours-per-week_normalized,combined-categories
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K,0.301370,0.800000,0.02174,0.0,0.397959,"[State-gov, Bachelors, Never-married, Adm-cler..."
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,0.452055,0.800000,0.00000,0.0,0.122449,"[Self-emp-not-inc, Bachelors, Married-civ-spou..."
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K,0.287671,0.533333,0.00000,0.0,0.397959,"[Private, HS-grad, Divorced, Handlers-cleaners..."
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K,0.493151,0.400000,0.00000,0.0,0.397959,"[Private, 11th, Married-civ-spouse, Handlers-c..."
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K,0.150685,0.800000,0.00000,0.0,0.397959,"[Private, Bachelors, Married-civ-spouse, Prof-..."

In [6]:
# window size of 8 includes all words in context
# ns_exponent of 0.0 samples all words equally
model = Word2Vec(list(normalized_data['combined-categories']), min_count=1, size=32, window=8, ns_exponent=0.0,
                 workers=8, iter=100)

In [7]:
# test vector for one of the categorical values
model['Private']

array([-2.578952  , -0.6876355 ,  0.7246369 ,  3.0531592 ,  1.5764028 ,
       -0.15761968,  1.2290756 , -0.81781876,  1.0244948 ,  3.3722653 ,
        0.23604755, -0.31962994,  0.67706615, -2.8283284 , -0.8158421 ,
        1.894719  , -1.1924934 ,  1.5293962 ,  1.7478462 ,  0.593495  ,
       -0.8526286 , -0.55201924,  3.5184526 , -1.6493465 , -0.04734904,
       -1.0394765 , -2.2802563 ,  0.02570487, -0.5517284 ,  0.6096552 ,
       -0.14515014, -2.4506783 ], dtype=float32)

In [8]:
def getCategoryArray(x):
    arr = []
    for col in categorical:
        arr.append(model[x[col].strip()])
    return np.mean(np.array(arr), axis=0)

In [9]:
normalized_data['categories_arr'] = normalized_data.apply(getCategoryArray, axis=1)
normalized_data.head()

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,...,hours-per-week,native-country,income,age_normalized,education-num_normalized,capital-gain_normalized,capital-loss_normalized,hours-per-week_normalized,combined-categories,categories_arr
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,...,40.0,United-States,<=50K,0.301370,0.800000,0.02174,0.0,0.397959,"[State-gov, Bachelors, Never-married, Adm-cler...","[0.05405876, 0.10552399, -0.53281194, 1.090557..."
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,...,13.0,United-States,<=50K,0.452055,0.800000,0.00000,0.0,0.122449,"[Self-emp-not-inc, Bachelors, Married-civ-spou...","[-0.95433396, 1.0547469, 0.19864272, -0.124587..."
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,...,40.0,United-States,<=50K,0.287671,0.533333,0.00000,0.0,0.397959,"[Private, HS-grad, Divorced, Handlers-cleaners...","[-0.18355824, 0.066178665, 0.11822815, 1.26119..."
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,...,40.0,United-States,<=50K,0.493151,0.400000,0.00000,0.0,0.397959,"[Private, 11th, Married-civ-spouse, Handlers-c...","[-0.4803267, 0.5346969, 0.14648008, 0.96485925..."
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,...,40.0,Cuba,<=50K,0.150685,0.800000,0.00000,0.0,0.397959,"[Private, Bachelors, Married-civ-spouse, Prof-...","[-0.3705293, -0.6117546, 0.18555821, -0.291346..."

In [10]:
normalizer = np.amax(list(normalized_data['categories_arr'])) - np.amin(list(normalized_data['categories_arr']))

In [11]:
def getCombinedArray(x):
    arr = x['categories_arr']
    for col in numerical_normalized:
        arr = np.append(arr, x[col]*normalizer)
    return arr

In [12]:
normalized_data['combined_arr'] = normalized_data.apply(getCombinedArray, axis=1)
normalized_data.head()

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,...,native-country,income,age_normalized,education-num_normalized,capital-gain_normalized,capital-loss_normalized,hours-per-week_normalized,combined-categories,categories_arr,combined_arr
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,...,United-States,<=50K,0.301370,0.800000,0.02174,0.0,0.397959,"[State-gov, Bachelors, Never-married, Adm-cler...","[0.05405876, 0.10552399, -0.53281194, 1.090557...","[0.05405876040458679, 0.1055239886045456, -0.5..."
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,...,United-States,<=50K,0.452055,0.800000,0.00000,0.0,0.122449,"[Self-emp-not-inc, Bachelors, Married-civ-spou...","[-0.95433396, 1.0547469, 0.19864272, -0.124587...","[-0.9543339610099792, 1.0547468662261963, 0.19..."
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,...,United-States,<=50K,0.287671,0.533333,0.00000,0.0,0.397959,"[Private, HS-grad, Divorced, Handlers-cleaners...","[-0.18355824, 0.066178665, 0.11822815, 1.26119...","[-0.18355824053287506, 0.06617866456508636, 0...."
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,...,United-States,<=50K,0.493151,0.400000,0.00000,0.0,0.397959,"[Private, 11th, Married-civ-spouse, Handlers-c...","[-0.4803267, 0.5346969, 0.14648008, 0.96485925...","[-0.48032671213150024, 0.5346968770027161, 0.1..."
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,...,Cuba,<=50K,0.150685,0.800000,0.00000,0.0,0.397959,"[Private, Bachelors, Married-civ-spouse, Prof-...","[-0.3705293, -0.6117546, 0.18555821, -0.291346...","[-0.37052929401397705, -0.6117545962333679, 0...."

### Visualize

In [13]:
def performTSNE(df, col, out_x='x', out_y='y', verbose=1, perplexity=40, n_iter=500):
    '''
    perform tSNE (t-distributed Stochastic Neighbor Embedding).
    A tool to visualize high-dimensional data. It converts similarities between data points to joint probabilities and tries to minimize the Kullback-Leibler divergence between the joint probabilities of the low-dimensional embedding and the high-dimensional data. 
    input:
        df - data frame
        col - name of col with embedding data
        out_x - name of column to store x-coordinates
        out_y - name of column to store y-cordinates
        verbose - 
        perplexity - related to the number of nearest neighbors - usually a value between 5 and 50
        n_iter - number of iterations
    output:
        input df with 2 additional columns for x and y co-ordinates
    '''
    X = np.array(list(df[col]))
    time_start = time.time()
    tsne = TSNE(n_components=2, verbose=verbose, random_state=32, perplexity=perplexity, n_iter=n_iter)
    tsne_results = tsne.fit_transform(X)
    if verbose > 0:
        print('t-SNE done! Time elapsed: {} seconds'.format(time.time()-time_start))
    df[out_x] = tsne_results[:,0]
    df[out_y] = tsne_results[:,1]
    
    return df

In [14]:
normalized_data = performTSNE(normalized_data, 'combined_arr')

[t-SNE] Computing 121 nearest neighbors...
[t-SNE] Indexed 45222 samples in 0.844s...
[t-SNE] Computed neighbors for 45222 samples in 104.084s...
[t-SNE] Computed conditional probabilities for sample 1000 / 45222
[t-SNE] Computed conditional probabilities for sample 2000 / 45222
[t-SNE] Computed conditional probabilities for sample 3000 / 45222
[t-SNE] Computed conditional probabilities for sample 4000 / 45222
[t-SNE] Computed conditional probabilities for sample 5000 / 45222
[t-SNE] Computed conditional probabilities for sample 6000 / 45222
[t-SNE] Computed conditional probabilities for sample 7000 / 45222
[t-SNE] Computed conditional probabilities for sample 8000 / 45222
[t-SNE] Computed conditional probabilities for sample 9000 / 45222
[t-SNE] Computed conditional probabilities for sample 10000 / 45222
[t-SNE] Computed conditional probabilities for sample 11000 / 45222
[t-SNE] Computed conditional probabilities for sample 12000 / 45222
[t-SNE] Computed conditional probabilities for sample 13000 / 45222
[t-SNE] Computed conditional probabilities for sample 14000 / 45222
[t-SNE] Computed conditional probabilities for sample 15000 / 45222
[t-SNE] Computed conditional probabilities for sample 16000 / 45222
[t-SNE] Computed conditional probabilities for sample 17000 / 45222
[t-SNE] Computed conditional probabilities for sample 18000 / 45222
[t-SNE] Computed conditional probabilities for sample 19000 / 45222
[t-SNE] Computed conditional probabilities for sample 20000 / 45222
[t-SNE] Computed conditional probabilities for sample 21000 / 45222
[t-SNE] Computed conditional probabilities for sample 22000 / 45222
[t-SNE] Computed conditional probabilities for sample 23000 / 45222
[t-SNE] Computed conditional probabilities for sample 24000 / 45222
[t-SNE] Computed conditional probabilities for sample 25000 / 45222
[t-SNE] Computed conditional probabilities for sample 26000 / 45222
[t-SNE] Computed conditional probabilities for sample 27000 / 45222
[t-SNE] Computed conditional probabilities for sample 28000 / 45222
[t-SNE] Computed conditional probabilities for sample 29000 / 45222
[t-SNE] Computed conditional probabilities for sample 30000 / 45222
[t-SNE] Computed conditional probabilities for sample 31000 / 45222
[t-SNE] Computed conditional probabilities for sample 32000 / 45222
[t-SNE] Computed conditional probabilities for sample 33000 / 45222
[t-SNE] Computed conditional probabilities for sample 34000 / 45222
[t-SNE] Computed conditional probabilities for sample 35000 / 45222
[t-SNE] Computed conditional probabilities for sample 36000 / 45222
[t-SNE] Computed conditional probabilities for sample 37000 / 45222
[t-SNE] Computed conditional probabilities for sample 38000 / 45222
[t-SNE] Computed conditional probabilities for sample 39000 / 45222
[t-SNE] Computed conditional probabilities for sample 40000 / 45222
[t-SNE] Computed conditional probabilities for sample 41000 / 45222
[t-SNE] Computed conditional probabilities for sample 42000 / 45222
[t-SNE] Computed conditional probabilities for sample 43000 / 45222
[t-SNE] Computed conditional probabilities for sample 44000 / 45222
[t-SNE] Computed conditional probabilities for sample 45000 / 45222
[t-SNE] Computed conditional probabilities for sample 45222 / 45222
[t-SNE] Mean sigma: 0.227456
[t-SNE] KL divergence after 250 iterations with early exaggeration: 85.542831
[t-SNE] KL divergence after 500 iterations: 2.555346
t-SNE done! Time elapsed: 185.8681297302246 seconds

In [15]:
normalized_data.head()

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,...,age_normalized,education-num_normalized,capital-gain_normalized,capital-loss_normalized,hours-per-week_normalized,combined-categories,categories_arr,combined_arr,x,y
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,...,0.301370,0.800000,0.02174,0.0,0.397959,"[State-gov, Bachelors, Never-married, Adm-cler...","[0.05405876, 0.10552399, -0.53281194, 1.090557...","[0.05405876040458679, 0.1055239886045456, -0.5...",-15.523680,-16.512529
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,...,0.452055,0.800000,0.00000,0.0,0.122449,"[Self-emp-not-inc, Bachelors, Married-civ-spou...","[-0.95433396, 1.0547469, 0.19864272, -0.124587...","[-0.9543339610099792, 1.0547468662261963, 0.19...",-14.611279,-3.724535
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,...,0.287671,0.533333,0.00000,0.0,0.397959,"[Private, HS-grad, Divorced, Handlers-cleaners...","[-0.18355824, 0.066178665, 0.11822815, 1.26119...","[-0.18355824053287506, 0.06617866456508636, 0....",-3.346431,-11.048361
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,...,0.493151,0.400000,0.00000,0.0,0.397959,"[Private, 11th, Married-civ-spouse, Handlers-c...","[-0.4803267, 0.5346969, 0.14648008, 0.96485925...","[-0.48032671213150024, 0.5346968770027161, 0.1...",-9.714744,3.797339
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,...,0.150685,0.800000,0.00000,0.0,0.397959,"[Private, Bachelors, Married-civ-spouse, Prof-...","[-0.3705293, -0.6117546, 0.18555821, -0.291346...","[-0.37052929401397705, -0.6117545962333679, 0....",21.107243,-13.129002

In [16]:
alt.Chart(normalized_data).mark_circle().encode(
                        x='x',
                        y='y',
                        color = 'income',
                        tooltip=['age', 'workclass', 'education_level', 'education-num',
                                 'marital-status', 'occupation', 'relationship', 'race', 'sex',
                                 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']
                    ).properties(
                        width=800,
                        height=600
                    )

alt.Chart(...)

### Effect of Gender, Marital Status and Race

In [17]:
sex_selection = alt.selection_multi(fields=['sex'], name='sex')
marital_selection = alt.selection_multi(fields=['marital-status'], name='marital')
race_selection = alt.selection_multi(fields=['race'], name='race')

scatter_color = alt.condition(sex_selection | marital_selection | race_selection,
                      alt.Color('income:N'),
                      alt.value('lightgray'))

sex_color = alt.condition(sex_selection,
                      alt.value("#e45756"),
                      alt.value('lightgray'))

marital_color = alt.condition(marital_selection,
                      alt.value("#72b7b2"),
                      alt.value('lightgray'))

race_color = alt.condition(race_selection,
                      alt.value("#54a24b"),
                      alt.value('lightgray'))


sex_bar = alt.Chart(normalized_data).mark_bar().encode(
                            x= alt.X('count()', axis=alt.Axis(title='')),
                            y=  alt.Y('sex:N', sort='-x', 
                                      axis=alt.Axis(title='', 
                                                    labelFontSize=12,
                                                    ticks=False)),
                            color=sex_color
                        ).properties(
                            width=200,
                            height=80,
                            title="Sex"
                        ).add_selection(
                                sex_selection
                        )

marital_bar = alt.Chart(normalized_data).mark_bar().encode(
                            x= alt.X('count()', axis=alt.Axis(title='')),
                            y=  alt.Y('marital-status:N', sort='-x', 
                                      axis=alt.Axis(title='', 
                                                    labelFontSize=12,
                                                    ticks=False)),
                            color=marital_color
                        ).properties(
                            width=200,
                            height=250,
                            title="Marital Status"
                        ).add_selection(
                                marital_selection
                        )

race_bar = alt.Chart(normalized_data).mark_bar().encode(
                            x= alt.X('count()', axis=alt.Axis(title='')),
                            y=  alt.Y('race:N', sort='-x', 
                                      axis=alt.Axis(title='', 
                                                    labelFontSize=12,
                                                    ticks=False)),
                            color=race_color
                        ).properties(
                            width=200,
                            height=150,
                            title="Race"
                        ).add_selection(
                                race_selection
                        )

scatter = alt.Chart(normalized_data).mark_circle().encode(
                        x='x',
                        y='y',
                        color = scatter_color,
                        tooltip=['age', 'workclass', 'education_level', 'education-num',
                                 'marital-status', 'occupation', 'relationship', 'race', 'sex',
                                 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']
                    ).properties(
                        width=500,
                        height=500
                    ).add_selection(alt.selection_single())
                    # selection_single work arounf for vega-lite bug - to show tooltp
    
(scatter | (sex_bar & marital_bar & race_bar)).configure_legend(
                        orient='bottom'
                    )

alt.HConcatChart(...)

### Effect of Education Level, Workclass and Occupation

In [18]:
workclass_selection = alt.selection_multi(fields=['workclass'], name='workclass')
education_level_selection = alt.selection_multi(fields=['education_level'], name='education_level')
occupation_selection = alt.selection_multi(fields=['occupation'], name='occupation')

scatter_color = alt.condition(workclass_selection | education_level_selection | occupation_selection,
                      alt.Color('income:N'),
                      alt.value('lightgray'))

workclass_color = alt.condition(workclass_selection,
                      alt.value("#e45756"),
                      alt.value('lightgray'))

education_level_color = alt.condition(education_level_selection,
                      alt.value("#72b7b2"),
                      alt.value('lightgray'))

occupation_color = alt.condition(occupation_selection,
                      alt.value("#54a24b"),
                      alt.value('lightgray'))


workclass_bar = alt.Chart(normalized_data).mark_bar().encode(
                            x= alt.X('count()', axis=alt.Axis(title='')),
                            y=  alt.Y('workclass:N', sort='-x', 
                                      axis=alt.Axis(title='', 
                                                    labelFontSize=12,
                                                    ticks=False)),
                            color=workclass_color
                        ).properties(
                            width=200,
                            height=80,
                            title="Workclass"
                        ).add_selection(
                                workclass_selection
                        )

education_level_bar = alt.Chart(normalized_data).mark_bar().encode(
                            x= alt.X('count()', axis=alt.Axis(title='')),
                            y=  alt.Y('education_level:N', sort='-x', 
                                      axis=alt.Axis(title='', 
                                                    labelFontSize=12,
                                                    ticks=False)),
                            color=education_level_color
                        ).properties(
                            width=200,
                            height=250,
                            title="Education Level"
                        ).add_selection(
                                education_level_selection
                        )

occupation_bar = alt.Chart(normalized_data).mark_bar().encode(
                            x= alt.X('count()', axis=alt.Axis(title='')),
                            y=  alt.Y('occupation:N', sort='-x', 
                                      axis=alt.Axis(title='', 
                                                    labelFontSize=12,
                                                    ticks=False)),
                            color=occupation_color
                        ).properties(
                            width=200,
                            height=150,
                            title="Occupation"
                        ).add_selection(
                                occupation_selection
                        )

scatter = alt.Chart(normalized_data).mark_circle().encode(
                        x='x',
                        y='y',
                        color = scatter_color,
                        tooltip=['age', 'workclass', 'education_level', 'education-num',
                                 'marital-status', 'occupation', 'relationship', 'race', 'sex',
                                 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']
                    ).properties(
                        width=500,
                        height=500
                    ).add_selection(alt.selection_single())
                    # selection_single work arounf for vega-lite bug - to show tooltp
    
(scatter | (workclass_bar & education_level_bar & occupation_bar)).configure_legend(
                        orient='bottom'
                    )

alt.HConcatChart(...)

### Modeling

In [19]:
features = pd.DataFrame(normalized_data['combined_arr'].tolist())
income = normalized_data['income'].map({'<=50K':0, '>50K':1})

### Shuffle and Split Data

In [20]:
# Split the 'features' and 'income' data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, 
                                                    income, 
                                                    test_size = 0.2, 
                                                    random_state = 0)

# Show the results of the split
print("Training set has {:,} samples.".format(X_train.shape[0]))
print("Testing set has {:,} samples.".format(X_test.shape[0]))

Training set has 36,177 samples.
Testing set has 9,045 samples.

In [22]:
# Initialize the classifier
clf = RandomForestClassifier(random_state=23)

# Create the parameters list you wish to tune, using a dictionary if needed.
parameters = {'n_estimators':[60, 75],'max_depth':[12, 14],'min_samples_leaf':[5, 6]}

# Make an fbeta_score scoring object using make_scorer()
scorer = make_scorer(fbeta_score, beta=0.5)

# Perform grid search on the classifier using 'scorer' as the scoring method using GridSearchCV()
grid_obj = GridSearchCV(clf, parameters, scoring=scorer)

# Fit the grid search object to the training data and find the optimal parameters using fit()
grid_fit = grid_obj.fit(X_train,y_train)

# Get the estimator
best_clf = grid_fit.best_estimator_

print(grid_fit.best_estimator_)

# Make predictions using the unoptimized and model
predictions = (clf.fit(X_train, y_train)).predict(X_test)
time_start = time.time()
best_predictions = (best_clf.fit(X_train, y_train)).predict(X_test)
time_end = time.time()

# Report the before-and-afterscores
print("Unoptimized model\n------")
print("Accuracy score on testing data: {:.4f}".format(accuracy_score(y_test, predictions)))
print("F-score on testing data: {:.4f}".format(fbeta_score(y_test, predictions, beta = 0.5)))
print("\nOptimized Model\n------")
print("Final accuracy score on the testing data: {:.4f}".format(accuracy_score(y_test, best_predictions)))
print("Final F-score on the testing data: {:.4f}".format(fbeta_score(y_test, best_predictions, beta = 0.5)))
print("Time taken {:.4f}".format(time_end - time_start))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=14, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=75,
                       n_jobs=None, oob_score=False, random_state=23, verbose=0,
                       warm_start=False)
Unoptimized model
------
Accuracy score on testing data: 0.8376
F-score on testing data: 0.6695

Optimized Model
------
Final accuracy score on the testing data: 0.8605
Final F-score on the testing data: 0.7284
Time taken 5.5149